language: csharp
mono: none
dotnet: 2.1.403
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
os:
  - linux
  - osx
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; fi
before_script:
  - chmod +x ./build.sh
script:
  - ./build.sh